#!/bin/sh
#
# Start the ntpd
#

if [ -r "$SD/firmware/scripts/functions.sh" ]; then
  . "$SD/firmware/scripts/functions.sh"
else
  echo "Unable to load basic functions"
  exit 1
fi

NAME="ntpd"
DESC="NTP Daemon"
DAEMON="/usr/sbin/${NAME}"
DAEMON_OPTS="-p ${NTP_SERVER}"
PIDFILE="/var/run/${NAME}.pid"

check_daemon_bin "${DAEMON}" "${DESC}"

case "$1" in
    start)
        start_daemon
    ;;
    stop)
        stop_daemon "${PIDFILE}"
    ;;
    status)
        status_daemon
    ;;
    restart|reload)
        "$0" stop
        "$0" start
    ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
    ;;
esac

exit $?
