#!/bin/sh -l

local pid_file=/var/run/mqtt.pid

status() {
  [ -f $pid_file ] && kill -0 $(cat $pid_file) >/dev/null 2>&1 || return 1
}

start() {
  status || start-stop-daemon \
    --background \
    --exec mqtt \
    --make-pidfile \
    --oknodo \
    --pidfile $pid_file \
    --quiet \
    --start
}

stop() {
  status && start-stop-daemon \
    --oknodo \
    --pidfile $pid_file \
    --quiet \
    --stop
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  status)
    status
  ;;
esac

exit $?
