#!/bin/sh -l

enable() {
  # /mnt/data/imi/imi_init/S93miio_client
  binary enable /mnt/data/ot_wifi_tool/miio_client
  binary enable /mnt/data/ot_wifi_tool/miio_client_helper_nomqtt.sh
  # /mnt/data/imi/imi_init/S93miot_devicekit
  binary enable /mnt/data/miot/miot_devicekit
  # /mnt/data/imi/imi_init/S93miot_qrcode
  binary enable /mnt/data/miot/miot_qrcode.sh
  # /mnt/data/imi/imi_init/S95miio_smb
  binary enable /mnt/data/miio_smb/miio_smb
  # cron
  binary enable /mnt/data/miot/logmi.sh

  restartctl update miio_client --then="/mnt/data/ot_wifi_tool/miio_client -D"
  restartctl enable miio_client
  restartctl enable miio_client_helper
  restartctl enable miot_devicekit
  restartctl enable miio_smb
  restartctl reload

  echo "Cloud services are enabled."
}

disable() {
  restartctl disable miio_client
  restartctl disable miio_client_helper
  restartctl disable miot_devicekit
  restartctl disable miio_smb
  restartctl reload

  # /mnt/data/imi/imi_init/S93miio_client
  binary disable /mnt/data/ot_wifi_tool/miio_client
  binary disable /mnt/data/ot_wifi_tool/miio_client_helper_nomqtt.sh
  # /mnt/data/imi/imi_init/S93miot_devicekit
  binary disable /mnt/data/miot/miot_devicekit
  # /mnt/data/imi/imi_init/S93miot_qrcode
  binary disable /mnt/data/miot/miot_qrcode.sh
  # /mnt/data/imi/imi_init/S95miio_smb
  binary disable /mnt/data/miio_smb/miio_smb
  # cron
  binary disable /mnt/data/miot/logmi.sh

  echo "Cloud services are disabled."
}

state() {
  restartctl status miio_client || return $?
}

case "$1" in
  enable) enable;;
  disable) disable;;
  state) state;;
esac

exit $?
