#!/bin/sh -l

local pid_file=/var/run/mqtt.pid

enable() {
  restart create mqtt --pattern="$(which mqtt)" --then="$(which service) mqtt start"
  restart reload

  echo "MQTT is enabled."
}

disable() {
  restart delete mqtt
  restart reload
  service mqtt stop

  echo "MQTT is disabled."
}

state() {
  restart status mqtt || return $?
}

status() {
  [ -f $pid_file ] && kill -0 $(cat $pid_file) >/dev/null 2>&1 || return 1
}

start() {
  echo "Starting MQTT service."

  status || start-stop-daemon \
    --background \
    --exec mqtt \
    --make-pidfile \
    --oknodo \
    --pidfile $pid_file \
    --quiet \
    --start
}

stop() {
  echo "Stopping MQTT service."

  status && start-stop-daemon \
    --oknodo \
    --pidfile $pid_file \
    --quiet \
    --stop
}

case "$1" in
  enable) enable;;
  disable) disable;;
  state) state;;
  status) status;;
  start) start;;
  stop) stop;;
esac

exit $?
