#!/bin/sh -l

local pid_file=/var/run/night-mode.pid

enable() {
  restartctl create night-mode --then="$(which service) night-mode start"
  restartctl reload

  echo "Automatic night mode is enabled."
}

disable() {
  restartctl delete night-mode
  restartctl reload
  service night-mode stop

  echo "Automatic night mode is disabled."
}

state() {
  restartctl status night-mode || return $?
}

status() {
  [ -f $pid_file ] && kill -0 $(cat $pid_file) >/dev/null 2>&1 || return 1
}

start() {
  echo "Starting automatic night mode."

  eval "$(config | grep ^NIGHT_MODE_)"
  status || start-stop-daemon \
    --background \
    --exec night-mode \
    --make-pidfile \
    --oknodo \
    --pidfile $pid_file \
    --quiet \
    --start \
    -- \
      ${NIGHT_MODE_DELAY:+--delay=$NIGHT_MODE_DELAY} \
      ${NIGHT_MODE_EV_ON:+--ev-on=$NIGHT_MODE_EV_ON} \
      ${NIGHT_MODE_EV_OFF:+--ev-on=$NIGHT_MODE_EV_OFF} \
      ${NIGHT_MODE_IR_ON:+--ev-on=$NIGHT_MODE_IR_ON} \
      ${NIGHT_MODE_IR_OFF:+--ev-on=$NIGHT_MODE_IR_OFF}
}

stop() {
  echo "Stopping automatic night mode."

  status && start-stop-daemon \
    --oknodo \
    --pidfile $pid_file \
    --quiet \
    --stop
}

case "$1" in
  enable) enable;;
  disable) disable;;
  state) state;;
  status) status;;
  start) start;;
  stop) stop;;
esac

exit $?
