#!/bin/sh -l

enable() {
  # /mnt/data/imi/imi_init/S60miio_avstreamer
  binary enable /mnt/data/miio_av/miio_avstreamer
  restart enable miio_avstreamer
  restart reload

  echo "Streamer is enabled."
}

disable() {
  # /mnt/data/imi/imi_init/S60miio_avstreamer
  restart disable miio_avstreamer
  restart reload
  binary disable /mnt/data/miio_av/miio_avstreamer

  echo "Streamer is disabled."
}

state() {
  restart status miio_avstreamer || return $?
}

case "$1" in
  enable) enable;;
  disable) disable;;
  state) state;;
esac

exit $?
