#!/bin/sh

cp -r /etc/profile.d /tmp && mount --bind /tmp/profile.d /etc/profile.d
cat >/etc/profile.d/firmware.sh <<EOF
export FIRMWARE_PATH=$PWD
export LD_LIBRARY_PATH=\$FIRMWARE_PATH/lib:\$LD_LIBRARY_PATH
export PATH=\$FIRMWARE_PATH/bin:\$PATH
export SD_PATH=$SD_PATH
EOF
