#!/bin/sh -l

camera ir cut disable
camera led yellow disable

camera led blue $([ "$(config get INDICATOR || echo 1)" -eq 1 ] && echo enable || echo disable)
camera mode ceiling $([ "$(config get CEILING_MODE || echo 0)" -eq 1 ] && echo enable || echo disable)
camera mode night $([ "$(config get NIGHT_MODE || echo AUTO)" -eq 1 ] && echo enable || echo disable)
