#!/bin/sh -l

camera led yellow disable

[ "$(config get INDICATOR || echo 1)" -eq 1 ] && camera led blue enable
[ "$(config get CEILING || echo 0)" -eq 1 ] && camera mode ceiling enable
[ "$(config get NIGHT || echo 0)" -eq 1 ] && camera mode night enable
