#!/bin/sh -l

local ssid=$(config get WIFI_SSID)
[ -z "$ssid" ] && exit 0

local password=$(config get WIFI_PASSWORD)
local key_management=$([ -z "$password" ] && echo NONE || echo WPA-PSK)

update() {
  local parameter="$1"
  local value="$2"

  [ $(nvram get "$parameter") == "$value" ] && return 0

  updated=1
  nvram set "$parameter"="$value"
}

echo "Configuring WiFi to '$ssid'."

update miio_ssid "$ssid"
update miio_key_mgmt "$key_management"
update miio_passwd "$password"
update wifi_ready yes
[ "$updated" == "1" ] && nvram commit

pgrep wpa_supplicant >/dev/null && /mnt/data/imi/imi_init/S92wifi restart
