#!/bin/sh -l

HOSTNAME=${HOSTNAME:-$(nvram factory get mac | tr [:upper:] [:lower:] | tr -d :)}
echo "Setting hostname to '$HOSTNAME'."
hostname $HOSTNAME
echo $HOSTNAME >/tmp/hostname && mount --bind /tmp/hostname /etc/hostname
echo "127.0.0.1 localhost $HOSTNAME" >/tmp/hosts && mount --bind /tmp/hosts /etc/hosts
