#!/bin/sh

NAME="Ceiling Mode"
TYPE=switch

get_state() {
  camera mode ceiling status && echo ON || echo OFF
}

set_state() {
  camera mode ceiling $([ "$1" = ON ] && echo enable || echo disable)
  config set CEILING_MODE $([ "$1" = ON ] && echo 1 || echo 0)
}
