#!/bin/sh -l

local pid_file=/var/run/ntpd.pid

status() {
  [ -f $pid_file ] && kill -0 $(cat $pid_file) >/dev/null 2>&1 || return 1
}

start() {
  status || start-stop-daemon \
    --background \
    --exec ntpd \
    --make-pidfile \
    --oknodo \
    --pidfile $pid_file \
    --quiet \
    --start \
    -- -n -p "${NTP_SERVER:-pool.ntp.org}"
}

stop() {
  status && start-stop-daemon \
    --oknodo \
    --pidfile $pid_file \
    --quiet \
    --stop
}

case "$1" in
  start)
    echo "Starting NTP client."
    start
  ;;
  stop)
    echo "Stopping NTP client."
    stop
  ;;
  status)
    status
  ;;
esac

exit $?
