#!/bin/sh -l

if [ "${NIGHT_MODE:-AUTO}" = AUTO ]; then
  $FIRMWARE_PATH/etc/init.d/auto_night_mode start
else
  $FIRMWARE_PATH/etc/init.d/auto_night_mode stop
  night_mode $([ "$NIGHT_MODE" -eq 1 ] && echo --enable || echo --disable)
fi
