#!/bin/sh -l

local pid_file=/var/run/auto_night_mode.pid

status() {
  [ -f $pid_file ] && kill -0 $(cat $pid_file) >/dev/null 2>&1 || return 1
}

start() {
  status || start-stop-daemon \
    --background \
    --exec auto_night_mode \
    --make-pidfile \
    --oknodo \
    --pidfile $pid_file \
    --quiet \
    --start \
    -- ${NIGHT_MODE_AUTO_ARGS:---ev-on 30 --ir-on 90 --ev-off 1000 --ir-off 100 --delay 5 --set-ircut --set-irled}
}

stop() {
  status && start-stop-daemon \
    --oknodo \
    --pidfile $pid_file \
    --quiet \
    --stop
}

case "$1" in
  start)
    echo "Starting automatic night mode."
    start
  ;;
  stop)
    echo "Stopping automatic night mode."
    stop
  ;;
  status)
    status
  ;;
esac

exit $?
