#!/bin/sh

copy() {
  local path=`dirname $(realpath $0)`

  cp -f $path/patch $path/prikey.pem $path/rsa_decrypt /mnt/data/ft
}

patch_ota() {
  local pre_ota=/mnt/data/miio_ota/pre-ota.sh
  local pre_ota_patch='cp -rf /mnt/data/ft /tmp/ft.bak'
  grep -q "$pre_ota_patch" $pre_ota || sed -e '\~^#!/bin/sh$~a\' -e "$pre_ota_patch" -i $pre_ota

  local post_ota=/mnt/data/miio_ota/post-ota.sh
  local post_ota_patch='/tmp/ft.bak/patch ota'
  grep -q "$post_ota_patch" $post_ota || sed -e '\~^#!/bin/sh$~a\' -e "$post_ota_patch" -i $post_ota
}

defer_patch_ota() {
  cp -f $0 /mnt/data/imi/imi_init/S00patch
}

case "$1" in
  start)
    patch_ota
    rm $0
  ;;
  ota)
    copy
    defer_patch_ota
  ;;
  *)
    copy
    patch_ota
esac
