#!/bin/sh

./patch

if [ -d /mnt/media/mmcblk0p1 ]; then
  sd="/mnt/media/mmcblk0p1"
elif [ -d /mnt/media/mmcblk0 ]; then
  sd="/mnt/media/mmcblk0"
fi

[ -f $sd/manufacture.dat ] && mv -f $sd/manufacture.dat $sd/manufacture.dat.bak
[ -f $sd/manufacture.bin ] && rm $sd/manufacture.bin
[ ! -f $sd/tf_recovery.img ] && reboot
