#!/bin/sh

mkdir -p /tmp/restartd
touch /tmp/restartd/restartd
cp /mnt/data/restartd/restartd.conf /tmp/restartd
mount --bind /mnt/data/restartd/restartd /tmp/restartd/restartd
mount --rbind /tmp/restartd /mnt/data/restartd
sed -i 's~^miio_client .*~miio_client "/mnt/data/ot_wifi_tool/miio_client -D" "/mnt/data/imi/imi_init/S93miio_client start" "/bin/echo '\''miio_client is running'\''"~' /mnt/data/restartd/restartd.conf
echo "restartd \"/mnt/data/restartd/restartd\" \"/mnt/data/imi/imi_init/S99restartd restart\" \"/bin/echo 'restartd is running'\"" >> /mnt/data/restartd/restartd.conf
