#!/bin/sh -l

[ -z "$TZ" ] && exit 0

echo "Setting timezone to '$TZ'."
[ -f /usr/share/zoneinfo/uclibc/$TZ ] && mount --bind /usr/share/zoneinfo/uclibc/$TZ /etc/localtime
echo $TZ >/tmp/TZ && mount --bind /tmp/TZ /etc/TZ
